/* NI01, UNITS.H */


#ifndef __UNITS_H__
#define __UNITS_H__

#include "anim.h"

/* COW unit
 * creation function */
in1UNIT * IN1_CowUnitCreate( VOID );

/* INFO Display unit
 * creation function */
in1UNIT * IN1_INFODisplayUnitCreate( VOID );

/* INFO Display unit
 * creation function */
in1UNIT * IN1_LOGOUnitCreate( VOID ); 

in1UNIT * IN1_CowboyUnitCreate( VOID );

in1UNIT * IN1_CUBEUnitCreate( VOID );

in1UNIT * IN1_SMTHUnitCreate( INT I );


#endif /* __UNITS_H__ */
